### GET request to example server
#GET https://examples.http-client.intellij.net/get?generated-in=PhpStorm

###
POST https://tickets-please.test/api/login?email=4Hn0r@example.com&password=password1234
Accept: application/json

###
